### ISSUE TITLE
TV norm prox

### ISSUE THREAD

**Issue by fabian-sp** [kul-forbes/ProximalOperators.jl#124]
Have you included the prox of the total variation norm, i.e. sum_i |x_i - x_{i-1}|?

I have implemented Condats algorithm in order to compute this (https://lcondat.github.io/publis/Condat-fast_TV-SPL-2013.pdf).
I could share my code.

Cheers!

**Comment by lostella** [comment]
I believe it’s not there in the package. Does the prox have closed form? Is it just for 1D signals or also 2D?

A PR is of course welcome :-) but let me know in case you need guidance there

**Comment by fabian-sp** [comment]
No, the prox is computed iteratively (see the referenced article). I think there is also a 2D version which would be useful for imaging problems I guess, but have not looked at that yet.
I would need at least some guidance on where to add the function :)

**Comment by lostella** [comment]
Of course! You can just add a source file in https://github.com/JuliaFirstOrder/ProximalOperators.jl/tree/master/src/functions say named tvnorm.jl and have the function type defined there. You can take a look at other source files there on how to organize it.

Only the call and `prox!` methods are strictly required (for other types, a `prox_naive` function is defined for testing purposes, but it maybe not needed in this case since there’s really no naive way of computing prox).

**Comment by fabian-sp** [comment]
Not sure whether you are interested in this, but one could also add some sum of norms, e.g. 1norm+2norm or 1norm+TV. Those are used in Group Lasso or Fused Lasso for example and the proximal operators can be shown to be just the concatenation of the individual proxes (in the right order).

**Comment by lostella** [comment]
@fabian-sp do you have references for those?

**Comment by fabian-sp** [comment]
1norm + 2norm: Proposition 2.1 in https://arxiv.org/pdf/1712.05910.pdf
1norm + TV: Proposition 4 in https://arxiv.org/pdf/1706.08732.pdf
