### ISSUE TITLE
SqrNormL2 expects λ to be positive 

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [kul-forbes/ProximalOperators.jl#139]
The upgrade to v. 0.15.0 breaks my code as SqrNormL2 now expects λ to be positive instead of non-negative. I would like to regularize only some of the parameters in my model, and achieved this by setting some values in the array λ to zero. What is the reason for this change? I would probably now go ahead and define my own proximal operator that works with 0-valued λs.

**Comment by lostella** [comment]
You’re right, I think this was an unnecessary breaking change. The reason for it was that `is_strongly_convex` could become a predicate of a type rather than an instance. I overlooked this, but the fix should be easy: we can store an additional boolean as type parameter, to be set at construction time to `all(lambda .> 0)`.

I’ll fix it, apologies for the inconvenience, and thanks for pointing this out!

**Comment by Maximilian-Stefan-Ernst** [comment]
Cool, thanks!!

**Comment by lostella** [comment]
@Maximilian-Stefan-Ernst fix merged, being released with 0.15.2 (registration in progress)
