### ISSUE TITLE
Prox of Sum

### ISSUE THREAD

**Issue by nxtruong** [kul-forbes/ProximalOperators.jl#90]
I have a sum of multiple functions (each is a `LeastSquare`):
```
f = Sum(f1, f2, f3)
```
`f` can be evaluated but `prox(f, x)` gives an error. Apparently, `prox` is not (yet) defined for `Sum`. Is that correct? If it is, any idea on when it will be added?

Thanks a lot.

**Comment by lostella** [comment]
Hi @nxtruong, the problem is that the proximal operator of the sum of functions is not always easily computable (it's usually not), so a generic implementation of `prox` for `Sum` will likely not be added.

However, this is doable in very specific cases like yours. The sum of `LeastSquares` functions is still a `LeastSquares` function, so if you stack matrices `A` and vectors `b` defining `f1`, `f2`, and `f3`, you'll get an equivalent `f`:

```julia
f = LeastSquares(vcat(A1, A2, A3), vcat(b1, b2, b3))
```

You can verify that such `f` is equivalent to the one you construct (e.g. by checking its value at specific points `x`). Hope this helps, feel free to follow up if you have further questions!

**Comment by lostella** [comment]
Here's an example of what I meant above:

```julia
A1, A2, A3 = randn(2, 5), randn(3, 5), randn(4, 5)
b1, b2, b3 = randn(2), randn(3), randn(4)
f1, f2, f3 = LeastSquares(A1, b1), LeastSquares(A2, b2), LeastSquares(A3, b3)
f = Sum(f1, f2, f3)
f_alt = LeastSquares(vcat(A1, A2, A3), vcat(b1, b2, b3))
x = randn(5)
f(x) - f_alt(x)  # this quantity will be very small or zero
```
